[package]
name = "fluent-bit-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
ropey = "1.6.1"
serde = "1.0.197"
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
tower-lsp = "0.20.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tree-sitter = "0.20.10"
tree-sitter-fluentbit = "0.1.0-alpha.1"
tree-sitter-traversal = "0.1.2"

[build-dependencies]
cc = "*"
