[workspace]
members = [
    "fluent-bit-language-server",
    "xtask",
]
resolver = "2"

[workspace.package]
rust-version = "1.80"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.86"
