[package]
name = "xtask"
version = "0.0.0"
publish = false

edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.13", features = ["derive"] }
flate2 = "1.0.31"
time = "0.3.36"
xshell = "0.2.6"
zip = "2.1.6"
